#Requires -Version 7.0
<#
.SYNOPSIS
    Setup script for Password-Generator-Advanced
    Generated by GitHub Universal Scaffolding Generator

.DESCRIPTION
    Creates the GitHub repository, initializes git, validates markdown,
    and pushes the initial scaffolding.

.NOTES
    Prerequisites: gh auth login (one-time GitHub authentication)

.EXAMPLE
    .\setup.ps1
#>

$ErrorActionPreference = "Stop"

$ProjectName = "Password-Generator-Advanced"
$Author = "valorisa"
$Visibility = "public"
$Description = "Générateur de mots de passe avec un menu interactif et obligation pour la création des mots de passe d'avoir des lettres minuscules, majuscules, chiffres, caractères spéciaux et un minimum de 9 chiffres et 9 caractères spéciaux."

Write-Host ""
Write-Host "=== Setup: $ProjectName ===" -ForegroundColor Cyan
Write-Host ""

# 1. Verify gh CLI is authenticated
Write-Host "[1/6] Checking GitHub CLI authentication..." -ForegroundColor Yellow
$authStatus = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: GitHub CLI not authenticated." -ForegroundColor Red
    Write-Host "Run 'gh auth login' first, then re-run this script."
    exit 1
}
$ghUser = gh api user -q ".login"
Write-Host "  OK - Authenticated as $ghUser" -ForegroundColor Green

# 2. Confirm repository details before creation
Write-Host ""
Write-Host "[2/6] Confirm repository details:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Repository : $Author/$ProjectName"
Write-Host "  Visibility : $Visibility"
Write-Host "  Description: $Description"
Write-Host ""
$NewName = Read-Host "Change repository name? (Enter = keep '$ProjectName', or type new name)"
if ($NewName -ne "") {
    $ProjectName = $NewName
    Write-Host "  -> Repository name changed to: $Author/$ProjectName" -ForegroundColor Cyan
}
Write-Host ""
$Confirm = Read-Host "Proceed with creation? (Y/n)"
if ($Confirm -match "^[Nn]") {
    Write-Host "Aborted." -ForegroundColor Gray
    exit 0
}

# 3. Create the repository on GitHub
Write-Host ""
Write-Host "[3/6] Creating repository $Author/$ProjectName ($Visibility)..." -ForegroundColor Yellow
$repoExists = gh repo view "$Author/$ProjectName" 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "  Repository already exists, skipping creation." -ForegroundColor Gray
} else {
    gh repo create "$Author/$ProjectName" --$Visibility --description "$Description"
    Write-Host "  Repository created." -ForegroundColor Green
}

# 4. Initialize git and set remote
Write-Host ""
Write-Host "[4/6] Initializing git repository..." -ForegroundColor Yellow
if (Test-Path .git) {
    Write-Host "  Git already initialized, skipping." -ForegroundColor Gray
} else {
    git init
    git remote add origin "https://github.com/$Author/$ProjectName.git"
    Write-Host "  Git initialized with remote origin." -ForegroundColor Green
}

# 5. Verify markdown (optional, non-blocking)
Write-Host ""
Write-Host "[5/6] Checking markdown files..." -ForegroundColor Yellow
$npxExists = Get-Command npx -ErrorAction SilentlyContinue
if ($npxExists) {
    npx markdownlint-cli2 "**/*.md"
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  Markdown OK" -ForegroundColor Green
    } else {
        Write-Host "  Warnings found (non-blocking)" -ForegroundColor DarkYellow
        $LASTEXITCODE = 0
    }
} else {
    Write-Host "  npx not found, skipping markdown check." -ForegroundColor Gray
}

# 6. Commit and push
Write-Host ""
Write-Host "[6/6] Committing and pushing to GitHub..." -ForegroundColor Yellow
git add .
git commit -m "feat: initial scaffolding via GitHub Universal Scaffolding Generator"
git branch -M main
git push -u origin main

Write-Host ""
Write-Host "=== Done! ===" -ForegroundColor Green
Write-Host ""
Write-Host "Your repository is live at: https://github.com/$Author/$ProjectName" -ForegroundColor Cyan
Write-Host ""
