#!/usr/bin/env bash
set -euo pipefail

# Setup script for Password-Generator-Advanced
# Generated by GitHub Universal Scaffolding Generator
#
# Prerequisites:
#   gh auth login   (one-time GitHub authentication)
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh

PROJECT_NAME="Password-Generator-Advanced"
AUTHOR="valorisa"
VISIBILITY="public"
DESCRIPTION="Generateur de mots de passe securises en ligne de commande avec contraintes cryptographiques strictes : minimum 9 chiffres, 9 caracteres speciaux, 1 minuscule, 1 majuscule. Utilise le module Python secrets (CSPRNG) pour une generation cryptographiquement sure. Menu interactif, generation unitaire ou par lot (1-50), composition detaillee affichee."
HOMEPAGE="https://github.com/${AUTHOR}/${PROJECT_NAME}"
TOPICS="password-generator,python,security,cli,secrets,cryptography,csprng,password-security,interactive-menu,python312,poetry,mit-license,command-line-tool,secure-passwords,character-constraints,batch-generation,password-strength,open-source,cross-platform,terminal-app"

echo ""
echo "=== Setup: ${PROJECT_NAME} ==="
echo ""

# 1. Verify gh CLI is authenticated
echo "[1/8] Checking GitHub CLI authentication..."
if ! gh auth status >/dev/null 2>&1; then
    echo "ERROR: GitHub CLI not authenticated."
    echo "Run 'gh auth login' first, then re-run this script."
    exit 1
fi
echo "  OK - Authenticated as $(gh api user -q .login)"

# 2. Confirm repository details before creation
echo ""
echo "[2/8] Confirm repository details:"
echo ""
echo "  Repository : ${AUTHOR}/${PROJECT_NAME}"
echo "  Visibility : ${VISIBILITY}"
echo "  Description: ${DESCRIPTION}"
echo "  Homepage   : ${HOMEPAGE}"
echo "  Topics     : ${TOPICS}"
echo ""
read -rp "Change repository name? (Enter = keep '${PROJECT_NAME}', or type new name): " NEW_NAME
if [ -n "${NEW_NAME}" ]; then
    PROJECT_NAME="${NEW_NAME}"
    HOMEPAGE="https://github.com/${AUTHOR}/${PROJECT_NAME}"
    echo "  → Repository name changed to: ${AUTHOR}/${PROJECT_NAME}"
fi
echo ""
read -rp "Proceed with creation? (Y/n): " CONFIRM
if [[ "${CONFIRM}" =~ ^[Nn] ]]; then
    echo "Aborted."
    exit 0
fi

# 3. Create the repository on GitHub
echo ""
echo "[3/8] Creating repository ${AUTHOR}/${PROJECT_NAME} (${VISIBILITY})..."
if gh repo view "${AUTHOR}/${PROJECT_NAME}" >/dev/null 2>&1; then
    echo "  Repository already exists, skipping creation."
else
    gh repo create "${AUTHOR}/${PROJECT_NAME}" --"${VISIBILITY}" --description "${DESCRIPTION}"
    echo "  Repository created."
fi

# 4. Configure About section (description, homepage, topics)
echo ""
echo "[4/8] Configuring repository About section..."
gh repo edit "${AUTHOR}/${PROJECT_NAME}" \
    --description "${DESCRIPTION}" \
    --homepage "${HOMEPAGE}"
echo "  Description and homepage set."

# 5. Set topics (20 labels)
echo ""
echo "[5/8] Setting repository topics..."
IFS=',' read -ra TOPIC_ARRAY <<< "${TOPICS}"
for topic in "${TOPIC_ARRAY[@]}"; do
    echo "  + ${topic}"
done
gh api -X PUT "repos/${AUTHOR}/${PROJECT_NAME}/topics" \
    -f names="$(echo "${TOPICS}" | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')" \
    --silent 2>/dev/null || \
gh api -X PUT "repos/${AUTHOR}/${PROJECT_NAME}/topics" \
    --input <(echo "{\"names\":[$(echo "${TOPICS}" | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/')]}") \
    --silent
echo "  20 topics set."

# 6. Initialize git and set remote
echo ""
echo "[6/8] Initializing git repository..."
if [ -d .git ]; then
    echo "  Git already initialized, skipping."
else
    git init
    git remote add origin "https://github.com/${AUTHOR}/${PROJECT_NAME}.git"
    echo "  Git initialized with remote origin."
fi

# 7. Verify markdown (optional, non-blocking)
echo ""
echo "[7/8] Checking markdown files..."
if command -v npx >/dev/null 2>&1; then
    if npx markdownlint-cli2 "**/*.md"; then
        echo "  Markdown OK (0 errors)"
    else
        echo ""
        echo "  Warning: Markdown violations found."
        echo "  You can fix them manually, then re-run this script."
        echo ""
        read -rp "Push anyway? (y/N): " PUSH_ANYWAY
        if [[ ! "${PUSH_ANYWAY}" =~ ^[Yy] ]]; then
            echo "Aborted. Fix the markdown issues and re-run ./setup.sh"
            exit 0
        fi
    fi
else
    echo "  npx not found, skipping markdown check."
    echo "  (Install Node.js to enable: npm install -g markdownlint-cli2)"
fi

# 8. Commit and push
echo ""
echo "[8/8] Committing and pushing to GitHub..."
git add .
git commit -m "feat: initial scaffolding via GitHub Universal Scaffolding Generator"
git branch -M main
git push -u origin main

echo ""
echo "=== Done! ==="
echo ""
echo "Your repository is live at: https://github.com/${AUTHOR}/${PROJECT_NAME}"
echo ""
echo "About section configured:"
echo "  Description : ${DESCRIPTION}"
echo "  Homepage    : ${HOMEPAGE}"
echo "  Topics (20) : ${TOPICS}"
echo ""
